<?php
// This script and data application were generated by AppGini 4.70
// Download AppGini for free from http://bigprof.com/appgini/download/

	$d=dirname(__FILE__);
	include("$d/defaultLang.php");
	include("$d/language.php");
	include("$d/lib.php");

	header("Content-type: text/javascript; charset=iso-8859-1");

	$mfk=$_GET['mfk'];
	$id=makeSafe($_GET['id']);
	$rnd1=intval($_GET['rnd1']); if(!$rnd1) $rnd1='';

	if(!$mfk){
		die('// no js code available!');
	}

	switch($mfk){

		case 'ProjectId':
			if($id) $res=sql("select * from `projects` where `Id`='$id' limit 1", $eo);
			if($id) $row=mysql_fetch_assoc($res);
			?>
			$('ProjectDuration<?php echo $rnd1; ?>').innerHTML='<?php echo addslashes(nl2br(($row['StartDate'] ? @date('d/m/Y', strtotime($row['StartDate'])) : '').' <b>to</b> '.($row['EndDate'] ? @date('d/m/Y', strtotime($row['EndDate'])) : ''))); ?>&nbsp;';
			<?php
			break;


	}

?>