<?php
// This script and data application were generated by AppGini 5.00
// Download AppGini for free from http://bigprof.com/appgini/download/

	/* Configuration */
	/*************************************/

		$pcConfig = array(
			'resources' => array(
			),
			'projects' => array(
			),
			'assignments' => array(
				'ProjectId' => array(
					'parent-table' => 'projects',
					'parent-primary-key' => 'Id',
					'child-primary-key' => 'Id',
					'child-primary-key-index' => 0,
					'tab-label' => 'Resources assigned',
					'table-icon' => 'resources/table_icons/client_account_template.png',
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => array(1 => 'Project', 3 => 'Resource', 4 => 'Commitment', 5 => 'Start Date', 6 => 'End Date'),
					'sortable-fields' => array(1 => '2', 3 => '4', 4 => '5', 5 => '`assignments`.`StartDate`', 6 => '`assignments`.`EndDate`'),
					'records-per-page' => 10,
					'default-sort-by' => false,
					'default-sort-direction' => 'asc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-assignments',
					'query' => "SELECT `assignments`.`Id` as 'Id', `projects1`.`Name` as 'ProjectId', if(char_length(`projects1`.`StartDate`) || char_length(`projects1`.`EndDate`), concat_ws('', if(`projects1`.`StartDate`,date_format(`projects1`.`StartDate`,'%d/%m/%Y'),''), ' <b>to</b> ', if(`projects1`.`EndDate`,date_format(`projects1`.`EndDate`,'%d/%m/%Y'),'')), '') as 'ProjectDuration', `resources1`.`Name` as 'ResourceId', `assignments`.`Commitment` as 'Commitment', if(`assignments`.`StartDate`,date_format(`assignments`.`StartDate`,'%d/%m/%Y'),'') as 'StartDate', if(`assignments`.`EndDate`,date_format(`assignments`.`EndDate`,'%d/%m/%Y'),'') as 'EndDate' FROM `assignments` LEFT JOIN `projects` as projects1 ON `assignments`.`ProjectId`=projects1.`Id` LEFT JOIN `resources` as resources1 ON `assignments`.`ResourceId`=resources1.`Id` "
				),
				'ResourceId' => array(
					'parent-table' => 'resources',
					'parent-primary-key' => 'Id',
					'child-primary-key' => 'Id',
					'child-primary-key-index' => 0,
					'tab-label' => 'Projects assigned',
					'table-icon' => 'resources/table_icons/client_account_template.png',
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => array(1 => 'Project', 3 => 'Resource', 4 => 'Commitment', 5 => 'Start Date', 6 => 'End Date'),
					'sortable-fields' => array(1 => '2', 3 => '4', 4 => '5', 5 => '`assignments`.`StartDate`', 6 => '`assignments`.`EndDate`'),
					'records-per-page' => 10,
					'default-sort-by' => false,
					'default-sort-direction' => 'asc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-assignments',
					'query' => "SELECT `assignments`.`Id` as 'Id', `projects1`.`Name` as 'ProjectId', if(char_length(`projects1`.`StartDate`) || char_length(`projects1`.`EndDate`), concat_ws('', if(`projects1`.`StartDate`,date_format(`projects1`.`StartDate`,'%d/%m/%Y'),''), ' <b>to</b> ', if(`projects1`.`EndDate`,date_format(`projects1`.`EndDate`,'%d/%m/%Y'),'')), '') as 'ProjectDuration', `resources1`.`Name` as 'ResourceId', `assignments`.`Commitment` as 'Commitment', if(`assignments`.`StartDate`,date_format(`assignments`.`StartDate`,'%d/%m/%Y'),'') as 'StartDate', if(`assignments`.`EndDate`,date_format(`assignments`.`EndDate`,'%d/%m/%Y'),'') as 'EndDate' FROM `assignments` LEFT JOIN `projects` as projects1 ON `assignments`.`ProjectId`=projects1.`Id` LEFT JOIN `resources` as resources1 ON `assignments`.`ResourceId`=resources1.`Id` "
				)
			)
		);

	/*************************************/
	/* End of configuration */


	@header("Content-Type: text/html; charset=iso-8859-1");
	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");

	/**
	* dynamic configuration based on current user's permissions
	* $userPCConfig array is populated only with parent tables where the user has access to
	* at least one child table
	*/
	$userPCConfig = array();
	foreach($pcConfig as $pcChildTable => $ChildrenLookups){
		$permChild = getTablePermissions($pcChildTable);
		if($permChild[2]){ // user can view records of the child table, so proceed to check children lookups
			foreach($ChildrenLookups as $ChildLookupField => $ChildConfig){
				$permParent = getTablePermissions($ChildConfig['parent-table']);
				if($permParent[2]){ // user can view records of parent table
					$userPCConfig[$pcChildTable][$ChildLookupField] = $pcConfig[$pcChildTable][$ChildLookupField];
					// show add new only if configured above AND the user has insert permission
					if($permChild[1] && $pcConfig[$pcChildTable][$ChildLookupField]['display-add-new']){
						$userPCConfig[$pcChildTable][$ChildLookupField]['display-add-new'] = true;
					}else{
						$userPCConfig[$pcChildTable][$ChildLookupField]['display-add-new'] = false;
					}
				}
			}
		}
	}

	/* Receive, UTF-convert, and validate parameters */
	$ParentTable = $_REQUEST['ParentTable']; // needed only with operation=show-children, will be validated in the processing code
	$ChildTable = $_REQUEST['ChildTable'];
		if(!in_array($ChildTable, array_keys($userPCConfig))){
			/* defaults to first child table in config array if not provided */
			$ChildTable = current(array_keys($userPCConfig));
		}
		if(!$ChildTable){ die('<!-- No tables accessible to current user -->'); }
	$SelectedID = $_REQUEST['SelectedID'];
	$ChildLookupField = $_REQUEST['ChildLookupField'];
		if(!in_array($ChildLookupField, array_keys($userPCConfig[$ChildTable]))){
			/* defaults to first lookup in current child config array if not provided */
			$ChildLookupField = current(array_keys($userPCConfig[$ChildTable]));
		}
	$Page = intval($_REQUEST['Page']);
		if($Page < 1){
			$Page = 1;
		}
	$SortBy = ($_REQUEST['SortBy'] != '' ? abs(intval($_REQUEST['SortBy'])) : false);
		if(!in_array($SortBy, array_keys($userPCConfig[$ChildTable][$ChildLookupField]['sortable-fields']), true)){
			$SortBy = $userPCConfig[$ChildTable][$ChildLookupField]['default-sort-by'];
		}
	$SortDirection = strtolower($_REQUEST['SortDirection']);
		if(!in_array($SortDirection, array('asc', 'desc'))){
			$SortDirection = $userPCConfig[$ChildTable][$ChildLookupField]['default-sort-direction'];
		}
	$Operation = strtolower($_REQUEST['Operation']);
		if(!in_array($Operation, array('get-records', 'show-children'))){
			$Operation = 'get-records';
		}

	/* process requested operation */
	switch($Operation){
		/************************************************/
		case 'show-children':
			/* populate HTML and JS content with children tabs */
			$tabLabels = $tabPanels = $tabEvents = $tabLoaders = '';
			foreach($userPCConfig as $ChildTable => $childLookups){
				foreach($childLookups as $ChildLookupField => $childConfig){
					if($childConfig['parent-table'] == $ParentTable){
						$TableIcon = ($childConfig['table-icon'] ? "<img src=\"{$childConfig['table-icon']}\" style=\"position: absolute; top: 3px; left: 3px;\" border=\"0\" />" : '');
						$tabLabels .= sprintf('<li class="TableBody"><a href="#%s-%s" id="tab_%s-%s" class="tab">%s%s</a></li>' . "\n\t\t\t\t\t", $ChildTable, $ChildLookupField, $ChildTable, $ChildLookupField, $TableIcon, $childConfig['tab-label']);
						$tabPanels .= sprintf('<div id="panel_%s-%s" class="panel" style="%s"><img src="loading.gif" align="top" />%s</div>' . "\n\t\t\t\t", $ChildTable, $ChildLookupField, ($tabPanels ? 'display: none;' : ''), $Translation['Loading ...']);
						$tabEvents .= '$$("#children-menu a").invoke("observe", "click", function(){ tabActivate(this); });' . "\n\t\t\t\t";
						$tabLoaders .= sprintf('post("parent-children.php", { ChildTable: "%s", ChildLookupField: "%s", SelectedID: "%s", Page: 1, SortBy: "", SortDirection: "", Operation: "get-records" }, "panel_%s-%s");' . "\n\t\t\t\t", $ChildTable, $ChildLookupField, addslashes($SelectedID), $ChildTable, $ChildLookupField);
					}
				}
			}

			if(!$tabLabels){ die('<!-- no children of current parent table are accessible to current user -->'); }
			?>
			<div id="children-menu">
				<ul>
					<?php echo $tabLabels; ?>
				</ul>
				<span id="pc-loading"></span>
			</div>
			<?php echo $tabPanels; ?>

			<script>
				/* add click handler for each tab */
				<?php echo $tabEvents; ?>

				/* ajax loading of each tab's contents */
				<?php echo $tabLoaders; ?>

				/* activate first tab */
				tabActivate($$("#children-menu a")[0]);

				/** function for changing the active tab */
				function tabActivate(tabLink){
					// if already activated, no need to continue
					if(tabLink.hasClassName('active')) return false;

					var panelId = tabLink.id.replace(/^tab_/, "panel_");
					$$(".panel").invoke("hide");
					$$("#children-menu a").invoke("removeClassName", "active");
					$$("#children-menu li").invoke("removeClassName", "TableHeader");
					$$("#children-menu li").invoke("addClassName", "TableBody");
					$(panelId).show();
					tabLink.addClassName("active").up().removeClassName("TableBody").addClassName("TableHeader");
					$$("li.TableHeader a").invoke("addClassName", "TableHeader");
					$$("li.TableHeader a").invoke("removeClassName", "TableBody");
					$$("li.TableBody a").invoke("addClassName", "TableBody");
					$$("li.TableBody a").invoke("removeClassName", "TableHeader");
				};
			</script>
			<?php
			break;

		/************************************************/
		default: /* default is 'get-records' */

			// build the user permissions limiter
			$permissionsWhere = $permissionsJoin = '';
			if($permChild[2] == 1){ // user can view only his own records
				$permissionsWhere = "`$ChildTable`.`{$userPCConfig[$ChildTable][$ChildLookupField]['child-primary-key']}`=`membership_userrecords`.`pkValue` AND `membership_userrecords`.`tableName`='$ChildTable' AND LCASE(`membership_userrecords`.`memberID`)='".getLoggedMemberID()."'";
			}elseif($permChild[2] == 2){ // user can view only his group's records
				$permissionsWhere = "`$ChildTable`.`{$userPCConfig[$ChildTable][$ChildLookupField]['child-primary-key']}`=`membership_userrecords`.`pkValue` AND `membership_userrecords`.`tableName`='$ChildTable' AND `membership_userrecords`.`groupID`='".getLoggedGroupID()."'";
			}elseif($permChild[2] == 3){ // user can view all records
				/* that's the only case remaining ... no need to modify the query in this case */
			}
			$permissionsJoin = ($permissionsWhere ? ", `membership_userrecords`" : '');

			// build the count query
			$forcedWhere = $userPCConfig[$ChildTable][$ChildLookupField]['forced-where'];
			$query = 
				preg_replace('/^select .* from /i', 'SELECT count(1) FROM ', $userPCConfig[$ChildTable][$ChildLookupField]['query']) .
				$permissionsJoin . " WHERE " .
				($permissionsWhere ? "( $permissionsWhere )" : "( 1=1 )") . " AND " .
				($forcedWhere ? "( $forcedWhere )" : "( 2=2 )") . " AND " .
				"`$ChildTable`.`$ChildLookupField`='" . makeSafe($SelectedID) . "'";
			$totalMatches = sqlValue($query);

			// make sure $Page is <= max pages
			$maxPage = ceil($totalMatches / $userPCConfig[$ChildTable][$ChildLookupField]['records-per-page']);
			if($Page > $maxPage){ $Page = $maxPage; }

			// initiate output data array
			$data = array(
				'config' => $userPCConfig[$ChildTable][$ChildLookupField],
				'parameters' => array(
					'ChildTable' => $ChildTable,
					'ChildLookupField' => $ChildLookupField,
					'SelectedID' => $SelectedID,
					'Page' => $Page,
					'SortBy' => $SortBy,
					'SortDirection' => $SortDirection,
					'Operation' => 'get-records'
				),
				'records' => array(),
				'totalMatches' => $totalMatches
			);

			// build the data query
			if($totalMatches){ // if we have at least one record, proceed with fetching data
				$startRecord = $userPCConfig[$ChildTable][$ChildLookupField]['records-per-page'] * ($Page - 1);
				$data['query'] = 
					$userPCConfig[$ChildTable][$ChildLookupField]['query'] .
					$permissionsJoin . " WHERE " .
					($permissionsWhere ? "( $permissionsWhere )" : "( 1=1 )") . " AND " .
					($forcedWhere ? "( $forcedWhere )" : "( 2=2 )") . " AND " .
					"`$ChildTable`.`$ChildLookupField`='" . makeSafe($SelectedID) . "'" . 
					($SortBy !== false ? " ORDER BY {$userPCConfig[$ChildTable][$ChildLookupField]['sortable-fields'][$SortBy]} $SortDirection" : '') .
					" LIMIT $startRecord, {$userPCConfig[$ChildTable][$ChildLookupField]['records-per-page']}";
				$res = sql($data['query'], $eo);
				while($row = mysql_fetch_row($res)){
					$data['records'][$row[$userPCConfig[$ChildTable][$ChildLookupField]['child-primary-key-index']]] = $row;
				}
			}else{ // if no matching records
				$startRecord = 0;
			}

			$response = loadView($userPCConfig[$ChildTable][$ChildLookupField]['template'], $data);

			// change name space to ensure uniqueness
			$uniqueNameSpace = $ChildTable.ucfirst($ChildLookupField).'GetRecords';
			echo str_replace("{$ChildTable}GetChildrenRecordsList", $uniqueNameSpace, $response);
		/************************************************/
	}
