<?php
// This script and data application were generated by AppGini 5.00
// Download AppGini for free from http://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/projects.php");
	include("$currDir/projects_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('projects');
	if(!$perm[0]){
		echo StyleSheet();
		echo "<div class=\"error\">".$Translation['tableAccessDenied']."</div>";
		echo '<script language="javaScript">setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "projects";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV=array(
		"`projects`.`Id`" => "Id",
		"`projects`.`Name`" => "Name",
		"if(`projects`.`StartDate`,date_format(`projects`.`StartDate`,'%d/%m/%Y'),'')" => "StartDate",
		"if(`projects`.`EndDate`,date_format(`projects`.`EndDate`,'%d/%m/%Y'),'')" => "EndDate"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`projects`.`Id`',
		2 => 2,
		3 => '`projects`.`StartDate`',
		4 => '`projects`.`EndDate`'
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV=array(
		"`projects`.`Id`" => "Id",
		"`projects`.`Name`" => "Name",
		"if(`projects`.`StartDate`,date_format(`projects`.`StartDate`,'%d/%m/%Y'),'')" => "StartDate",
		"if(`projects`.`EndDate`,date_format(`projects`.`EndDate`,'%d/%m/%Y'),'')" => "EndDate"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters=array(
		"`projects`.`Id`" => "ID",
		"`projects`.`Name`" => "Name",
		"`projects`.`StartDate`" => "Start Date",
		"`projects`.`EndDate`" => "End Date"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS=array(
		"`projects`.`Id`" => "Id",
		"`projects`.`Name`" => "Name",
		"if(`projects`.`StartDate`,date_format(`projects`.`StartDate`,'%d/%m/%Y'),'')" => "StartDate",
		"if(`projects`.`EndDate`,date_format(`projects`.`EndDate`,'%d/%m/%Y'),'')" => "EndDate"
	);

	$x->QueryFrom="`projects` ";
	$x->QueryWhere='';
	$x->QueryOrder='';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingMultiSelection = 0;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 3;
	$x->TablePaginationAlignment = 0;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "projects_view.php";
	$x->RedirectAfterInsert = "projects_view.php?SelectedID=#ID#";
	$x->TableTitle = "Projects";
	$x->TableIcon = "resources/table_icons/application_from_storage.png";
	$x->PrimaryKey = "`projects`.`Id`";

	$x->ColWidth   = array(150, 150, 150);
	$x->ColCaption = array("Name", "Start Date", "End Date");
	$x->ColNumber  = array(2, 3, 4);

	$x->Template = 'templates/projects_templateTV.html';
	$x->SelectedTemplate = 'templates/projects_templateTVS.html';
	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `projects`.`Id`=membership_userrecords.pkValue and membership_userrecords.tableName='projects' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `projects`.`Id`=membership_userrecords.pkValue and membership_userrecords.tableName='projects' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`projects`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: projects_init
	$render=TRUE;
	if(function_exists('projects_init')){
		$args=array();
		$render=projects_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: projects_header
	$headerCode='';
	if(function_exists('projects_header')){
		$args=array();
		$headerCode=projects_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include("$currDir/header.php"); 
	}else{
		ob_start(); include("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: projects_footer
	$footerCode='';
	if(function_exists('projects_footer')){
		$args=array();
		$footerCode=projects_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include("$currDir/footer.php"); 
	}else{
		ob_start(); include("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>